const RUN_POLICY = Object.freeze({
  MIN_SAVE_DISTANCE_KM: 0.1,
  MIN_SAVE_DURATION_SECONDS: 60,
  MIN_SAVE_COORDINATES: 6,
  MAX_ACCURACY_METERS: 100,
  JITTER_DISTANCE_METERS: 4,
  MAX_SEGMENT_SPEED_KMH: 30,
  STATIONARY_SPEED_THRESHOLD_KMH: 1.5
});

module.exports = RUN_POLICY;
