export const RUN_LEDGER_POLICY = Object.freeze({
  MIN_SAVE_DISTANCE_KM: 0.1,
  MIN_SAVE_DURATION_SECONDS: 60,
  MIN_SAVE_COORDINATES: 6,
  CORE_SAVE_MAX_ACCURACY: 30,
  JITTER_DISTANCE_METERS: 4,
  MAX_SEGMENT_SPEED_KMH: 30,
  STATIONARY_SPEED_THRESHOLD_KMH: 1.5,
} as const);

export const RUN_LIVE_POLICY = Object.freeze({
  LIVE_DISPLAY_MAX_ACCURACY: 100,
  LIVE_PACE_WINDOW_SECONDS: 12,
  LIVE_JITTER_DISTANCE_METERS: 1,
  LIVE_MAX_SEGMENT_SPEED_KMH: 180,
  STATIONARY_SPEED_THRESHOLD_KMH: 1.5,
} as const);

export const RUN_POLICY = Object.freeze({
  MIN_SAVE_DISTANCE_KM: RUN_LEDGER_POLICY.MIN_SAVE_DISTANCE_KM,
  MIN_SAVE_DURATION_SECONDS: RUN_LEDGER_POLICY.MIN_SAVE_DURATION_SECONDS,
  MIN_SAVE_COORDINATES: RUN_LEDGER_POLICY.MIN_SAVE_COORDINATES,
  CORE_SAVE_MAX_ACCURACY: RUN_LEDGER_POLICY.CORE_SAVE_MAX_ACCURACY,
  JITTER_DISTANCE_METERS: RUN_LEDGER_POLICY.JITTER_DISTANCE_METERS,
  MAX_SEGMENT_SPEED_KMH: RUN_LEDGER_POLICY.MAX_SEGMENT_SPEED_KMH,
  STATIONARY_SPEED_THRESHOLD_KMH: RUN_LEDGER_POLICY.STATIONARY_SPEED_THRESHOLD_KMH,
  MAX_ACCURACY_METERS: RUN_LEDGER_POLICY.CORE_SAVE_MAX_ACCURACY,
  LIVE_DISPLAY_MAX_ACCURACY: RUN_LIVE_POLICY.LIVE_DISPLAY_MAX_ACCURACY,
  LIVE_PACE_WINDOW_SECONDS: RUN_LIVE_POLICY.LIVE_PACE_WINDOW_SECONDS,
  LIVE_JITTER_DISTANCE_METERS: RUN_LIVE_POLICY.LIVE_JITTER_DISTANCE_METERS,
  LIVE_MAX_SEGMENT_SPEED_KMH: RUN_LIVE_POLICY.LIVE_MAX_SEGMENT_SPEED_KMH,
} as const);

export type RunLedgerPolicy = typeof RUN_LEDGER_POLICY;
export type RunLivePolicy = typeof RUN_LIVE_POLICY;
export type RunPolicy = typeof RUN_POLICY;

export const {
  MIN_SAVE_DISTANCE_KM,
  MIN_SAVE_DURATION_SECONDS,
  MIN_SAVE_COORDINATES,
  CORE_SAVE_MAX_ACCURACY,
  MAX_ACCURACY_METERS,
  JITTER_DISTANCE_METERS,
  MAX_SEGMENT_SPEED_KMH,
  STATIONARY_SPEED_THRESHOLD_KMH,
  LIVE_DISPLAY_MAX_ACCURACY,
  LIVE_PACE_WINDOW_SECONDS,
  LIVE_JITTER_DISTANCE_METERS,
  LIVE_MAX_SEGMENT_SPEED_KMH,
} = RUN_POLICY;
