export const RUN_LEDGER_POLICY = Object.freeze({
  MIN_SAVE_DISTANCE_KM: 0.1,
  MIN_SAVE_DURATION_SECONDS: 60,
  MIN_SAVE_COORDINATES: 6,
  CORE_SAVE_MAX_ACCURACY: 30,
  JITTER_DISTANCE_METERS: 4,
  MAX_SEGMENT_SPEED_KMH: 30,
  STATIONARY_SPEED_THRESHOLD_KMH: 1.5,
} as const);

export const RUN_LIVE_POLICY = Object.freeze({
  LIVE_DISPLAY_MAX_ACCURACY: 55,
  LIVE_PACE_WINDOW_SECONDS: 12,
  JITTER_DISTANCE_METERS: 4,
  MAX_SEGMENT_SPEED_KMH: 30,
  STATIONARY_SPEED_THRESHOLD_KMH: 1.5,
} as const);

export const RUN_POLICY = Object.freeze({
  ...RUN_LEDGER_POLICY,
  ...RUN_LIVE_POLICY,
  MAX_ACCURACY_METERS: RUN_LEDGER_POLICY.CORE_SAVE_MAX_ACCURACY,
} as const);

export type RunLedgerPolicy = typeof RUN_LEDGER_POLICY;
export type RunLivePolicy = typeof RUN_LIVE_POLICY;
export type RunPolicy = typeof RUN_POLICY;

export const {
  MIN_SAVE_DISTANCE_KM,
  MIN_SAVE_DURATION_SECONDS,
  MIN_SAVE_COORDINATES,
  CORE_SAVE_MAX_ACCURACY,
  MAX_ACCURACY_METERS,
  JITTER_DISTANCE_METERS,
  MAX_SEGMENT_SPEED_KMH,
  STATIONARY_SPEED_THRESHOLD_KMH,
  LIVE_DISPLAY_MAX_ACCURACY,
  LIVE_PACE_WINDOW_SECONDS,
} = RUN_POLICY;
